version: "2.4"

services:
  dspacedb:
    image: dspace/dspace-postgres-pgcrypto
    environment:
      - PGDATA=/pgdata
    volumes:
      - pgdata:/pgdata
    networks:
      - dspacenet
    tty: true
    stdin_open: true

  dspace:
    image: "dspace/dspace:dspace-6_x"
    mem_limit: 2048m
    environment:
      - DSPACE_INSTALL=/dspace
     # - JAVA_OPTS=-Dcom.sun.management.jmxremote.rmi.port=9090 -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=9090 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname=localhost
     # - JPDA_ADDRESS=9000
    ports:
      - 8080:8080
      - 9000:9000
     # - 9090:9090
    volumes:
      - "/apps/git/drum:/dspace-src"
      - "/apps/git/drum-env:/drum-env"
    networks:
      - dspacenet
    depends_on:
      - dspacedb
    tty: true
    stdin_open: true
    command:
      - catalina.sh
      - jpda
      - run

  dspacesolr:
    image: geerlingguy/solr:4.10.4
    ports:
     - "8983:8983"
    volumes:
      - "/apps/git/drum/dspace/solr:/config"
      - "/apps/git/drum/scripts/docker:/scripts"
      - solr:/var/solr/cores
    command: "/scripts/start.sh"
    networks:
      - dspacenet

  # dspacenginx:
  #   image: nginx
  #   depends_on: 
  #     - dspace
  #   ports: 
  #     - 80:80
  #   volumes:
  #     - /apps/git/drum/scripts/docker/nginx.conf:/etc/nginx/nginx.conf:ro 
  #   networks:
  #     - dspacenet
volumes:
  pgdata:
  solr:

networks:
  dspacenet: